<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GET_Method_Validation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4f7cfcaa-105a-4d8f-abf2-bf8ea1d0d8c3</testSuiteGuid>
   <testCaseLink>
      <guid>710a639a-11ee-477c-9658-7424592dd307</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GET-Method-Validation-TCs/SINGLE USER - Validation/GET_SINGLE_USER - VerifyResponseCode_AND_ResponseBody</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0eec79f3-3061-4778-ac30-2dcf8eaa1727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5d83604-1099-46d9-8edc-3a5b297feaf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb03c3e8-0268-404d-b32f-a29fc95a3ec1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>072c7ee8-a1a4-48fd-aabd-2a9bb3cd8ba4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>270d1589-b323-484a-a829-112de11d394a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GET-Method-Validation-TCs/SINGLE USER - Validation/GET_SINGLE_USER - VerifyResponseType</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8835b5a-b07e-4a6a-886f-045eaa8a0181</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3947e848-588f-4cdf-b4f2-57796ab502aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a61428c1-50c4-4c2c-bd01-ea26b376b59b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
